Vagrant.configure("2") do |config|
    # Guest VM Name, CentOS version for base box, shared folder
    vm_name = 'hdnode2.adtest07.org'
    vagrant_arg = ARGV[0]
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"

    # Guest VM settings
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 4196]
        v.customize ["modifyvm", :id, "--cpus", "4"]
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
        v.customize ["modifyvm", :id, "--vram", "20"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.customize ["modifyvm", :id, "--usb", "off"]
        v.name = vm_name
    end

    # Set up a private IP that can be added to the host machine's hosts file
    config.vm.network "private_network", ip: "192.168.99.12"

    config.vm.hostname = vm_name

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "provisioning/vagrant_playbook.yml"
        # ansible.verbose = "v"
    end
    config.vm.provision :reload 
end
